// Frozen Playwright v1.57.0 DOWNLOAD_PATHS for Chromium and headless shell.
// Used to pin legacyPathTemplates after Playwright switched to Chrome for Testing.

const DOWNLOAD_PATHS = {
  'chromium': {
    '<unknown>': undefined,
    'ubuntu18.04-x64': undefined,
    'ubuntu20.04-x64': 'builds/chromium/%s/chromium-linux.zip',
    'ubuntu22.04-x64': 'builds/chromium/%s/chromium-linux.zip',
    'ubuntu24.04-x64': 'builds/chromium/%s/chromium-linux.zip',
    'ubuntu18.04-arm64': undefined,
    'ubuntu20.04-arm64': 'builds/chromium/%s/chromium-linux-arm64.zip',
    'ubuntu22.04-arm64': 'builds/chromium/%s/chromium-linux-arm64.zip',
    'ubuntu24.04-arm64': 'builds/chromium/%s/chromium-linux-arm64.zip',
    'debian11-x64': 'builds/chromium/%s/chromium-linux.zip',
    'debian11-arm64': 'builds/chromium/%s/chromium-linux-arm64.zip',
    'debian12-x64': 'builds/chromium/%s/chromium-linux.zip',
    'debian12-arm64': 'builds/chromium/%s/chromium-linux-arm64.zip',
    'debian13-x64': 'builds/chromium/%s/chromium-linux.zip',
    'debian13-arm64': 'builds/chromium/%s/chromium-linux-arm64.zip',
    'mac10.13': 'builds/chromium/%s/chromium-mac.zip',
    'mac10.14': 'builds/chromium/%s/chromium-mac.zip',
    'mac10.15': 'builds/chromium/%s/chromium-mac.zip',
    'mac11': 'builds/chromium/%s/chromium-mac.zip',
    'mac11-arm64': 'builds/chromium/%s/chromium-mac-arm64.zip',
    'mac12': 'builds/chromium/%s/chromium-mac.zip',
    'mac12-arm64': 'builds/chromium/%s/chromium-mac-arm64.zip',
    'mac13': 'builds/chromium/%s/chromium-mac.zip',
    'mac13-arm64': 'builds/chromium/%s/chromium-mac-arm64.zip',
    'mac14': 'builds/chromium/%s/chromium-mac.zip',
    'mac14-arm64': 'builds/chromium/%s/chromium-mac-arm64.zip',
    'mac15': 'builds/chromium/%s/chromium-mac.zip',
    'mac15-arm64': 'builds/chromium/%s/chromium-mac-arm64.zip',
    'win64': 'builds/chromium/%s/chromium-win64.zip',
  },
  'chromium-headless-shell': {
    '<unknown>': undefined,
    'ubuntu18.04-x64': undefined,
    'ubuntu20.04-x64': 'builds/chromium/%s/chromium-headless-shell-linux.zip',
    'ubuntu22.04-x64': 'builds/chromium/%s/chromium-headless-shell-linux.zip',
    'ubuntu24.04-x64': 'builds/chromium/%s/chromium-headless-shell-linux.zip',
    'ubuntu18.04-arm64': undefined,
    'ubuntu20.04-arm64': 'builds/chromium/%s/chromium-headless-shell-linux-arm64.zip',
    'ubuntu22.04-arm64': 'builds/chromium/%s/chromium-headless-shell-linux-arm64.zip',
    'ubuntu24.04-arm64': 'builds/chromium/%s/chromium-headless-shell-linux-arm64.zip',
    'debian11-x64': 'builds/chromium/%s/chromium-headless-shell-linux.zip',
    'debian11-arm64': 'builds/chromium/%s/chromium-headless-shell-linux-arm64.zip',
    'debian12-x64': 'builds/chromium/%s/chromium-headless-shell-linux.zip',
    'debian12-arm64': 'builds/chromium/%s/chromium-headless-shell-linux-arm64.zip',
    'debian13-x64': 'builds/chromium/%s/chromium-headless-shell-linux.zip',
    'debian13-arm64': 'builds/chromium/%s/chromium-headless-shell-linux-arm64.zip',
    'mac10.13': undefined,
    'mac10.14': undefined,
    'mac10.15': undefined,
    'mac11': 'builds/chromium/%s/chromium-headless-shell-mac.zip',
    'mac11-arm64': 'builds/chromium/%s/chromium-headless-shell-mac-arm64.zip',
    'mac12': 'builds/chromium/%s/chromium-headless-shell-mac.zip',
    'mac12-arm64': 'builds/chromium/%s/chromium-headless-shell-mac-arm64.zip',
    'mac13': 'builds/chromium/%s/chromium-headless-shell-mac.zip',
    'mac13-arm64': 'builds/chromium/%s/chromium-headless-shell-mac-arm64.zip',
    'mac14': 'builds/chromium/%s/chromium-headless-shell-mac.zip',
    'mac14-arm64': 'builds/chromium/%s/chromium-headless-shell-mac-arm64.zip',
    'mac15': 'builds/chromium/%s/chromium-headless-shell-mac.zip',
    'mac15-arm64': 'builds/chromium/%s/chromium-headless-shell-mac-arm64.zip',
    'win64': 'builds/chromium/%s/chromium-headless-shell-win64.zip',
  },
};
